### ISSUE TITLE
Update alloy/Plugin/Spot to latest version

### ISSUE THREAD

**Issue by mwoc** [alloyphp/alloy#15]
i've been trying to get the latest Spot version working with the plugin, but the namespaces seem to have changed in Spot, and I cant figure out how to account for that within the plugin. Can anyone help with this or could it be done by someone directly in this repo?

**Comment by vlucas** [comment]
Spot ORM has been updated.

SHA: f20fddb90898d7cc449db6f9c1c155a8d92986ce
